; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui +Resize

Gui Font, s16, Lucida Console
Gui Add, Edit, x0 y0 w599 h429 +Multi, `n     __,---.__`n  ,-'         ``-.__`n&/           ``._\ _\`n/               ''._`n|   ,             (")`n|__,'``-..--|__|--''
Gui Font

Gui Show, w599 h429, pig
Return

GuiEscape:
GuiClose:
    ExitApp

