println("            __,---.__")
println("         ,-'         `-.__")
println("       &/           `._\\ _\\")
println("       /               ''._")
println("       |   ,             ('')")
println("       |__,'`-..--|__|--''")