; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui +Resize
Menu FileMenu, Add, &New`tCtrl+N, MenuHandler
Menu FileMenu, Add, &Open...`tCtrl+O, MenuHandler
Menu FileMenu, Add, &Save`tCtrl+S, MenuHandler
Menu FileMenu, Add, Save &As..., MenuHandler
Menu FileMenu, Add
Menu FileMenu, Add, Page Set&up..., MenuHandler
Menu FileMenu, Add, &Print...`tCtrl+P, MenuHandler
Menu FileMenu, Add
Menu FileMenu, Add, E&xit, MenuHandler
Menu EditMenu, Add, &Undo`tCtrl+Z, MenuHandler
Menu EditMenu, Add
Menu EditMenu, Add, Cu&t`tCtrl+X, MenuHandler
Menu EditMenu, Add, &Copy`tCtrl+C, MenuHandler
Menu EditMenu, Add, &Paste`tCtrl+V, MenuHandler
Menu EditMenu, Add, De&lete`tDel, MenuHandler
Menu EditMenu, Add
Menu EditMenu, Add, &Find...`tCtrl+F, MenuHandler
Menu EditMenu, Add, Find &Next`tF3, MenuHandler
Menu EditMenu, Add, &Replace...`tCtrl+H, MenuHandler
Menu EditMenu, Add, &Go To...`tCtrl+G, MenuHandler
Menu EditMenu, Add
Menu EditMenu, Add, Select &All`tCtrl+A, MenuHandler
Menu EditMenu, Add, Time/&Date`tF5, MenuHandler
Menu FormatMenu, Add, &Word Wrap, MenuHandler
Menu FormatMenu, Add, &Font..., MenuHandler
Menu ViewMenu, Add, &Status Bar, MenuHandler
Menu HelpMenu, Add, View &Help, MenuHandler
Menu HelpMenu, Add
Menu HelpMenu, Add, &About Notepad, MenuHandler
Menu MenuBar, Add, &File, :FileMenu
Menu MenuBar, Add, &Edit, :EditMenu
Menu MenuBar, Add, F&ormat, :FormatMenu
Menu MenuBar, Add, &View, :ViewMenu
Menu MenuBar, Add, &Help, :HelpMenu
Gui Menu, MenuBar

Gui Font, s16, Lucida Console
Gui Add, Edit, x0 y0 w599 h429 +Multi, `n           __,---.__`n        ,-'         ``-.__`n      &/           ``._\ _\`n      /               ''._`n      |   ,             (")`n      |__,'``-..--|__|--''
Gui Font

Gui Show, w599 h429, pig.txt - Notepad
Return

GuiEscape:
GuiClose:
    ExitApp
